name: Сборка frontend-проекта
on: push
jobs:
  build-front:
    name: Build front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build container
        run: echo "Hello"
